# Generated by Django 3.2.5 on 2022-01-23 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_eventos_usuario_alter_eventos_data_criacao_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventos',
            name='local',
            field=models.TextField(blank=True, null=True),
        ),
    ]
